import Head from "next/head"
import Image from "next/image"
import HAbout from "../components/home/HAbout"
import AboutCard from "../components/about/AboutCard"
import Hero from "../components/home/hero/Hero"
import styles from "../styles/Home.module.css"
import Testimonal from "../components/home/testimonal/Testimonal"
import Hblog from "../components/home/Hblog"
import Hprice from "../components/home/Hprice"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Academia | DinWebDev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-1.ico" />
      </Head>

      <Hero />
      <AboutCard />
      <HAbout />
      <Testimonal />
      <Hblog />
      <Hprice />
    </div>
  )
}
